// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkforceHubAPI.Repository;

#nullable disable

namespace WorkforceHubAPI.WebAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241209022309_AddRefreshTokenFields")]
    partial class AddRefreshTokenFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "456ac4f6-d40a-437b-ad56-02dc4ca48af4",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3e0eed4f-1476-4ca7-9f5a-bc4cf6dc7f27",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WorkforceHubAPI.Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Address = "123 Silicon Street, East Legon, Accra",
                            Country = "Ghana",
                            Name = "AccraTech Solutions"
                        },
                        new
                        {
                            Id = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Address = "45 Ashanti Way, Adum, Kumasi",
                            Country = "Ghana",
                            Name = "Kumasi Innovations"
                        },
                        new
                        {
                            Id = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Address = "78 Ocean Drive, Cape Coast",
                            Country = "Ghana",
                            Name = "Cape Coast Ventures"
                        },
                        new
                        {
                            Id = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Address = "89 Harbor Road, Takoradi",
                            Country = "Ghana",
                            Name = "Takoradi Energy Systems"
                        },
                        new
                        {
                            Id = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Address = "456 Port Lane, Tema",
                            Country = "Ghana",
                            Name = "Tema Logistics Hub"
                        },
                        new
                        {
                            Id = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Address = "34 Green Street, Sunyani",
                            Country = "Ghana",
                            Name = "Sunyani AgroTech"
                        },
                        new
                        {
                            Id = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Address = "12 Volt Road, Ho",
                            Country = "Ghana",
                            Name = "Ho Digital Services"
                        },
                        new
                        {
                            Id = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Address = "56 Savannah Way, Tamale",
                            Country = "Ghana",
                            Name = "Tamale Business Solutions"
                        },
                        new
                        {
                            Id = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Address = "89 Northern Road, Bolgatanga",
                            Country = "Ghana",
                            Name = "Bolgatanga Rural Enterprises"
                        },
                        new
                        {
                            Id = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Address = "34 Upper West Lane, Wa",
                            Country = "Ghana",
                            Name = "Wa Regional Tech"
                        },
                        new
                        {
                            Id = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Address = "67 Coastline Avenue, Sekondi",
                            Country = "Ghana",
                            Name = "Sekondi Marine Services"
                        },
                        new
                        {
                            Id = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Address = "98 Eastern Road, Koforidua",
                            Country = "Ghana",
                            Name = "Koforidua Tech Hub"
                        });
                });

            modelBuilder.Entity("WorkforceHubAPI.Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Age = 26,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Sam Raiden",
                            Position = "Software Developer"
                        },
                        new
                        {
                            Id = new Guid("1a283b1d-ecf4-4a62-bfc0-b4a07cc1b54a"),
                            Age = 30,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Linda Akpene",
                            Position = "UI/UX Designer"
                        },
                        new
                        {
                            Id = new Guid("24ab8f3d-6783-4327-963b-c13c63bc285a"),
                            Age = 35,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Kwame Asante",
                            Position = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("c01a3e8d-1493-4ca1-bbc2-2b5be7a217f7"),
                            Age = 28,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Evelyn Osei",
                            Position = "Marketing Specialist"
                        },
                        new
                        {
                            Id = new Guid("bb742a8e-1be2-4cc0-8e0c-ec545b168943"),
                            Age = 32,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Isaac Owusu",
                            Position = "Backend Developer"
                        },
                        new
                        {
                            Id = new Guid("79c55ab3-d5bc-441d-b885-38cabe3f659b"),
                            Age = 29,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Kwabena Amankwah",
                            Position = "Product Designer"
                        },
                        new
                        {
                            Id = new Guid("dc2efdc5-bfdd-4a0f-90b2-081ed9c17f87"),
                            Age = 27,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Ama Nkrumah",
                            Position = "Frontend Developer"
                        },
                        new
                        {
                            Id = new Guid("a30d4e91-b6fe-4774-b43e-0fc72fef0169"),
                            Age = 31,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Kwasi Nkrumah",
                            Position = "DevOps Engineer"
                        },
                        new
                        {
                            Id = new Guid("e69a8f02-0930-4f07-9da9-90227b89ae6b"),
                            Age = 26,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Kofi Agyekum",
                            Position = "Business Analyst"
                        },
                        new
                        {
                            Id = new Guid("31adf02b-63d7-40c0-83f9-588ea6e8465b"),
                            Age = 28,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Selina Otieno",
                            Position = "Database Administrator"
                        },
                        new
                        {
                            Id = new Guid("dfad8187-1a69-4637-b4be-9b84d1a430b2"),
                            Age = 30,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Nana Ama",
                            Position = "Sales Manager"
                        },
                        new
                        {
                            Id = new Guid("b06e76c5-6635-47cd-bfbc-22a970953118"),
                            Age = 34,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Richard Ansah",
                            Position = "Network Engineer"
                        },
                        new
                        {
                            Id = new Guid("a87b3a9c-b2f9-4609-a9b9-ea80b6e32a60"),
                            Age = 28,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Kwame Boakye",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("7c60b745-bd6c-44b5-b31c-4d975f0a1e64"),
                            Age = 32,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Ama Mensah",
                            Position = "Digital Marketing Specialist"
                        },
                        new
                        {
                            Id = new Guid("ab29fa9c-0a8c-43b9-b36c-c8b7905959b2"),
                            Age = 29,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Yaw Ofori",
                            Position = "Frontend Developer"
                        },
                        new
                        {
                            Id = new Guid("8be53912-2879-46ed-918b-6abff8b8a76e"),
                            Age = 30,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Evelyn Appiah",
                            Position = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("1a6a35b6-cf47-4bbf-bbb0-c5e43b17b503"),
                            Age = 34,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Kwasi Fosu",
                            Position = "Business Analyst"
                        },
                        new
                        {
                            Id = new Guid("530f68bb-9ad6-4e5e-b2da-bf6a2324ff2a"),
                            Age = 27,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Martha Aidoo",
                            Position = "Backend Developer"
                        },
                        new
                        {
                            Id = new Guid("12545e89-d7e9-4fd6-bd33-3cf3e8d3272f"),
                            Age = 29,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Kofi Ntow",
                            Position = "UI/UX Designer"
                        },
                        new
                        {
                            Id = new Guid("d95c5c3f-f2e4-4fe2-9797-939b63e73b51"),
                            Age = 31,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Selina Obeng",
                            Position = "Network Engineer"
                        },
                        new
                        {
                            Id = new Guid("4063c586-1497-411f-8b74-28a6a53f3ff2"),
                            Age = 30,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Kwabena Afriyie",
                            Position = "System Administrator"
                        },
                        new
                        {
                            Id = new Guid("bdc51cf2-2f0b-4a6c-9298-8c8d00405639"),
                            Age = 27,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Kwame Kwaku",
                            Position = "DevOps Engineer"
                        },
                        new
                        {
                            Id = new Guid("18f69f4e-0d34-4c19-b7e3-70c973d5f121"),
                            Age = 25,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Akua Asare",
                            Position = "Sales Manager"
                        },
                        new
                        {
                            Id = new Guid("ab177301-cada-4190-8f5c-c2ff62d86cd0"),
                            Age = 33,
                            CompanyId = new Guid("d1f8d4a7-cc3e-4429-a5dc-55a7b8c7b22c"),
                            Name = "Selorm Aklamanu",
                            Position = "Database Administrator"
                        },
                        new
                        {
                            Id = new Guid("8db43067-b4bb-46f2-9083-bc7ca37025a0"),
                            Age = 27,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Kofi Mensah",
                            Position = "Software Developer"
                        },
                        new
                        {
                            Id = new Guid("9a776712-8428-4c61-b388-86bcbb98607a"),
                            Age = 30,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Akosua Asamoah",
                            Position = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("6f087b39-c8a7-417f-98c1-9b9e1ad0327f"),
                            Age = 33,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Kwame Owusu",
                            Position = "Frontend Developer"
                        },
                        new
                        {
                            Id = new Guid("8355b262-58c1-4b96-b85a-292bfc1d7b7d"),
                            Age = 29,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Abena Adomako",
                            Position = "Marketing Specialist"
                        },
                        new
                        {
                            Id = new Guid("d201d6d4-bd5f-4c27-b2ba-b302b4c6a9f9"),
                            Age = 28,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Yaw Afful",
                            Position = "Backend Developer"
                        },
                        new
                        {
                            Id = new Guid("e764879d-bd6f-4de0-bb19-18dcb09d07b5"),
                            Age = 31,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Martha Osei",
                            Position = "Business Analyst"
                        },
                        new
                        {
                            Id = new Guid("41208e82-cf02-4b1f-b0ba-f51ec8a212f1"),
                            Age = 34,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Kwabena Amoah",
                            Position = "DevOps Engineer"
                        },
                        new
                        {
                            Id = new Guid("a84d5c6c-b00c-44e2-85fa-9783248f6652"),
                            Age = 26,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Selina Ofori",
                            Position = "HR Manager"
                        },
                        new
                        {
                            Id = new Guid("5684c3b4-63d4-44db-a923-3e92a7a72055"),
                            Age = 29,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Kwame Buadi",
                            Position = "System Administrator"
                        },
                        new
                        {
                            Id = new Guid("01805b3d-7178-4c8b-bff5-e53bb9d40819"),
                            Age = 32,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Akua Osei",
                            Position = "Sales Manager"
                        },
                        new
                        {
                            Id = new Guid("2a8dff97-7628-4dbf-aad3-240e957c5f77"),
                            Age = 30,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Selorm Appiah",
                            Position = "Software Architect"
                        },
                        new
                        {
                            Id = new Guid("f501c1a2-c69c-4d84-baa3-0215687032a3"),
                            Age = 27,
                            CompanyId = new Guid("e6e97850-2e1c-4573-bb49-9d46cde3fc4c"),
                            Name = "Kwesi Oteng",
                            Position = "Database Administrator"
                        },
                        new
                        {
                            Id = new Guid("c72b39d0-36f6-42c6-81b0-dc85fc9f65b7"),
                            Age = 29,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Kwame Agyemang",
                            Position = "Electrical Engineer"
                        },
                        new
                        {
                            Id = new Guid("a651649d-d9a0-4be3-b268-b51e22921f3a"),
                            Age = 31,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Esi Mensah",
                            Position = "Safety Officer"
                        },
                        new
                        {
                            Id = new Guid("baf6ab35-178d-49f0-b810-970b4eb908f4"),
                            Age = 27,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Abena Opoku",
                            Position = "Field Technician"
                        },
                        new
                        {
                            Id = new Guid("cb8a682b-4926-4423-8f98-c8b3b32ea707"),
                            Age = 35,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Yaw Asare",
                            Position = "Mechanical Engineer"
                        },
                        new
                        {
                            Id = new Guid("b0c3720d-58ad-46c5-9887-b2490cfc4677"),
                            Age = 32,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Kofi Boateng",
                            Position = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("df99867f-5e47-4b7d-8c7d-84a55a6efca1"),
                            Age = 29,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Selina Ofori",
                            Position = "HR Manager"
                        },
                        new
                        {
                            Id = new Guid("b89f6a5f-1f22-4311-b957-e545bc3f7c89"),
                            Age = 33,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Akua Ansah",
                            Position = "Finance Manager"
                        },
                        new
                        {
                            Id = new Guid("cc2549a1-c0f8-4f1a-8ad7-4f2a951d9ac1"),
                            Age = 30,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Kwabena Addo",
                            Position = "Electrical Design Engineer"
                        },
                        new
                        {
                            Id = new Guid("fb93d477-35f8-420f-b45a-3bc313bfa11b"),
                            Age = 28,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Abdul Aziz",
                            Position = "Procurement Officer"
                        },
                        new
                        {
                            Id = new Guid("e6d1e63f-3bb2-4f2d-bcb3-bc64e4791f5e"),
                            Age = 26,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Grace Osei",
                            Position = "Laboratory Technician"
                        },
                        new
                        {
                            Id = new Guid("346a2790-1d42-4264-83d9-c2dfe4e25c1d"),
                            Age = 36,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Kojo Frimpong",
                            Position = "Operations Supervisor"
                        },
                        new
                        {
                            Id = new Guid("f741e561-dde5-4e13-b8a2-84e489da1289"),
                            Age = 30,
                            CompanyId = new Guid("b7bce287-c37f-411e-b9f4-3c34f53b7c7c"),
                            Name = "Martha Mensah",
                            Position = "Environmental Engineer"
                        },
                        new
                        {
                            Id = new Guid("11831acb-b219-4557-a748-b1e01d041c51"),
                            Age = 32,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Kwaku Nyarko",
                            Position = "Logistics Coordinator"
                        },
                        new
                        {
                            Id = new Guid("fdde8c11-4133-46a5-a0c4-14b39d6a8fd5"),
                            Age = 29,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Yaa Ampomah",
                            Position = "Inventory Manager"
                        },
                        new
                        {
                            Id = new Guid("33e7a41a-9512-47f5-96be-7cc3f5d4043b"),
                            Age = 30,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Kwabena Bempah",
                            Position = "Warehouse Supervisor"
                        },
                        new
                        {
                            Id = new Guid("02b6c2be-60f5-4133-8282-0cfc05558cc9"),
                            Age = 27,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Abena Appiah",
                            Position = "Supply Chain Analyst"
                        },
                        new
                        {
                            Id = new Guid("4d478d92-3b7e-4ff0-94ac-736619b9a4d2"),
                            Age = 33,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Kofi Adomako",
                            Position = "Logistics Manager"
                        },
                        new
                        {
                            Id = new Guid("74a9a2b0-ea2a-43d2-8a75-5b249e1b62ab"),
                            Age = 34,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Kwame Frimpong",
                            Position = "Transport Manager"
                        },
                        new
                        {
                            Id = new Guid("c99b80f2-f8b3-4204-b7f0-e5f9b3cae013"),
                            Age = 28,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Martha Boateng",
                            Position = "Fleet Coordinator"
                        },
                        new
                        {
                            Id = new Guid("b76739c2-8995-4551-bc5c-f16c274e14b7"),
                            Age = 31,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Ama Owusu",
                            Position = "Customer Service Representative"
                        },
                        new
                        {
                            Id = new Guid("678ec9c0-97d4-4d18-a38d-f0f7883a8bcb"),
                            Age = 29,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Kojo Baidoo",
                            Position = "Procurement Officer"
                        },
                        new
                        {
                            Id = new Guid("ddf4e9ed-b459-4a1b-832d-d4a2d63cd3ba"),
                            Age = 28,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Selina Kwarteng",
                            Position = "Operations Manager"
                        },
                        new
                        {
                            Id = new Guid("b774a4db-b55f-470b-b648-24f493f85de4"),
                            Age = 35,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Kwabena Owusu",
                            Position = "Supply Chain Coordinator"
                        },
                        new
                        {
                            Id = new Guid("57717f61-0700-4a2d-b167-47316d0fcfe3"),
                            Age = 30,
                            CompanyId = new Guid("a8c963a3-8fb8-41b2-a6cc-cb87c689d62d"),
                            Name = "Akosua Frempong",
                            Position = "Warehouse Associate"
                        },
                        new
                        {
                            Id = new Guid("1ac1c94a-ea9b-4c13-8d7c-96b697d2b53f"),
                            Age = 32,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Kofi Adu",
                            Position = "Agronomist"
                        },
                        new
                        {
                            Id = new Guid("948b9b8a-24de-4379-9fe2-dad8d347c920"),
                            Age = 30,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Akosua Sarpong",
                            Position = "Supply Chain Coordinator"
                        },
                        new
                        {
                            Id = new Guid("19a3bb85-bdc5-4641-9413-bd50b7a51a6d"),
                            Age = 35,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Yaw Kwaku",
                            Position = "Field Supervisor"
                        },
                        new
                        {
                            Id = new Guid("fae211f4-55ab-47da-a464-fb62fd8de35b"),
                            Age = 29,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Grace Osei",
                            Position = "Marketing Officer"
                        },
                        new
                        {
                            Id = new Guid("69fc3c71-8d8c-4022-ae16-cb0497be2c55"),
                            Age = 28,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Kojo Frimpong",
                            Position = "Sales Executive"
                        },
                        new
                        {
                            Id = new Guid("5e93d1a9-5829-4020-89a3-dfca1d6c0ab1"),
                            Age = 33,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Selina Nkrumah",
                            Position = "HR Officer"
                        },
                        new
                        {
                            Id = new Guid("28b239d1-d3a3-4a99-9a11-ef238a91b9c4"),
                            Age = 27,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Kwaku Adjei",
                            Position = "Agricultural Technician"
                        },
                        new
                        {
                            Id = new Guid("40b64968-d4d2-479a-bf6e-89d26f1e8d3f"),
                            Age = 34,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Akosua Agyemang",
                            Position = "Quality Control Manager"
                        },
                        new
                        {
                            Id = new Guid("16e2cfe6-3bb5-4f96-a0e5-547f234bd7ac"),
                            Age = 31,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Kojo Bempah",
                            Position = "Operations Manager"
                        },
                        new
                        {
                            Id = new Guid("c6d1c697-bba5-4b22-b622-63669b40c2f7"),
                            Age = 28,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Yaa Osei",
                            Position = "Procurement Assistant"
                        },
                        new
                        {
                            Id = new Guid("9487bbf5-fd1b-4025-803b-fb8e602d9433"),
                            Age = 26,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Abena Ofori",
                            Position = "Logistics Assistant"
                        },
                        new
                        {
                            Id = new Guid("ab216b1f-85ea-419b-99b8-85fd7d1d6727"),
                            Age = 29,
                            CompanyId = new Guid("f7b48b3b-4e2b-4d1a-8f61-9b7c7f8e2f73"),
                            Name = "Yaw Baidoo",
                            Position = "Product Development Officer"
                        },
                        new
                        {
                            Id = new Guid("b8f6a447-f3f7-44a3-8195-23d6345f4f2d"),
                            Age = 34,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Kwame Asante",
                            Position = "Construction Project Manager"
                        },
                        new
                        {
                            Id = new Guid("e94546f0-0c58-455d-bd98-7be2e3c777c3"),
                            Age = 29,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Akosua Owusu",
                            Position = "Site Supervisor"
                        },
                        new
                        {
                            Id = new Guid("62d3b5a5-d0b6-408b-bf62-83795fd7e3ff"),
                            Age = 28,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Yaw Kwaku",
                            Position = "Civil Engineer"
                        },
                        new
                        {
                            Id = new Guid("7f987cbe-e071-4628-b64a-e1f49f7b4b0c"),
                            Age = 30,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Esi Amoah",
                            Position = "Architect"
                        },
                        new
                        {
                            Id = new Guid("b281b67d-3683-4ca5-b6d4-684d937a1c36"),
                            Age = 33,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Kojo Bempah",
                            Position = "Construction Worker"
                        },
                        new
                        {
                            Id = new Guid("b709de80-b346-4baf-bb1b-4a8a1cd7d4c9"),
                            Age = 31,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Kwabena Frimpong",
                            Position = "Surveyor"
                        },
                        new
                        {
                            Id = new Guid("abe41745-c1f4-4a4e-8d09-df6b22ba53b4"),
                            Age = 27,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Akosua Afram",
                            Position = "Project Coordinator"
                        },
                        new
                        {
                            Id = new Guid("cfb17e10-8ec0-40ae-bca6-d3188e39a0c9"),
                            Age = 28,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Martha Boakye",
                            Position = "Logistics Manager"
                        },
                        new
                        {
                            Id = new Guid("1a145d32-c650-4f92-bc88-01ca36b827eb"),
                            Age = 32,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Yaw Frimpong",
                            Position = "Health & Safety Officer"
                        },
                        new
                        {
                            Id = new Guid("db38e0db-cb93-4c1a-9502-815c1c575d4b"),
                            Age = 30,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Kojo Osei",
                            Position = "Construction Laborer"
                        },
                        new
                        {
                            Id = new Guid("e3f462f1-92c5-463f-bc8a-2b212ea7e592"),
                            Age = 34,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Akua Boateng",
                            Position = "Quantity Surveyor"
                        },
                        new
                        {
                            Id = new Guid("379d7cfe-9c4f-44c1-b3a5-d63d4d5227e4"),
                            Age = 29,
                            CompanyId = new Guid("d3f4b98d-cd5e-4c43-a828-9c8e3d1f5b6a"),
                            Name = "Abena Baidoo",
                            Position = "Project Accountant"
                        },
                        new
                        {
                            Id = new Guid("e53ea087-c21b-4789-8290-9783fd3d6349"),
                            Age = 32,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Kwame Osei",
                            Position = "Automotive Engineer"
                        },
                        new
                        {
                            Id = new Guid("b3403b64-0880-4bb9-b9f6-c650c7f11fd4"),
                            Age = 29,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Akua Adu",
                            Position = "Workshop Manager"
                        },
                        new
                        {
                            Id = new Guid("9fc8b253-f91e-4b7a-a4fa-b5f9a9a64b98"),
                            Age = 30,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Kojo Asante",
                            Position = "Mechanic"
                        },
                        new
                        {
                            Id = new Guid("c8354b67-5572-4902-8538-b78b81890b72"),
                            Age = 33,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Yaa Frimpong",
                            Position = "Customer Service Representative"
                        },
                        new
                        {
                            Id = new Guid("7cc1c7c9-3f66-4646-bfb5-d4b076b091c3"),
                            Age = 27,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Selina Boakye",
                            Position = "Parts Manager"
                        },
                        new
                        {
                            Id = new Guid("824b670f-72ae-4a06-bdb0-1686a1b0f8be"),
                            Age = 35,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Kwabena Kwarteng",
                            Position = "Service Advisor"
                        },
                        new
                        {
                            Id = new Guid("0c106fd9-9027-402e-9ca0-e431b7a1bc39"),
                            Age = 28,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Abena Kwaku",
                            Position = "Automotive Technician"
                        },
                        new
                        {
                            Id = new Guid("9c26ad3b-17c2-4028-bf63-e01d5c9d0034"),
                            Age = 31,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Kojo Agyemang",
                            Position = "Auto Body Repair Specialist"
                        },
                        new
                        {
                            Id = new Guid("85d46022-7848-4694-b8f3-599c67ea79bb"),
                            Age = 30,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Yaa Nkrumah",
                            Position = "Inventory Coordinator"
                        },
                        new
                        {
                            Id = new Guid("da31e7ab-b8a9-47b0-9752-ff3e6822d6f4"),
                            Age = 33,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Yaw Akoto",
                            Position = "Test Driver"
                        },
                        new
                        {
                            Id = new Guid("45ed3c0b-d7fe-4a58-8cc6-f7773b23795f"),
                            Age = 29,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Akosua Bempah",
                            Position = "Sales Manager"
                        },
                        new
                        {
                            Id = new Guid("02c5e378-0be4-46bc-9268-93b57564cd99"),
                            Age = 34,
                            CompanyId = new Guid("c3e47a8b-d4cf-435d-927f-6b4e92a3f4c3"),
                            Name = "Kwame Kofi",
                            Position = "Business Development Officer"
                        },
                        new
                        {
                            Id = new Guid("4933bfc7-0f01-48ac-a26e-99f1f6bb6cf5"),
                            Age = 31,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Kwame Akoto",
                            Position = "Operations Manager"
                        },
                        new
                        {
                            Id = new Guid("f25a1c12-23c4-4b7b-83fa-b98a93961d90"),
                            Age = 29,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Akosua Nkrumah",
                            Position = "Agriculture Specialist"
                        },
                        new
                        {
                            Id = new Guid("99ae6b0e-25e6-4609-8a5d-09848f75ecbb"),
                            Age = 28,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Yaw Kwaku",
                            Position = "Business Analyst"
                        },
                        new
                        {
                            Id = new Guid("d7cc1297-c455-49f4-b6ff-846f36d40b2f"),
                            Age = 34,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Kojo Owusu",
                            Position = "Marketing Officer"
                        },
                        new
                        {
                            Id = new Guid("27cfb8a0-bff1-4f8a-967b-5b12c623af9b"),
                            Age = 32,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Abena Asare",
                            Position = "Project Coordinator"
                        },
                        new
                        {
                            Id = new Guid("0ef8297b-1a8f-42a6-83f3-c0e3a2ea74bb"),
                            Age = 30,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Martha Afia",
                            Position = "Supply Chain Manager"
                        },
                        new
                        {
                            Id = new Guid("94de5454-2cbf-4673-9237-e9d111b39c76"),
                            Age = 33,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Kwabena Frimpong",
                            Position = "Production Manager"
                        },
                        new
                        {
                            Id = new Guid("81024367-6ed0-4170-ae44-56b54e12bfe7"),
                            Age = 29,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Yaa Akosua",
                            Position = "Human Resources Manager"
                        },
                        new
                        {
                            Id = new Guid("abb8d054-d875-406a-8a98-5ad38a1eb697"),
                            Age = 28,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Kojo Baidoo",
                            Position = "Customer Service Officer"
                        },
                        new
                        {
                            Id = new Guid("f25154b1-e702-47c9-a7d6-6599be5c5b56"),
                            Age = 30,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Akua Appiah",
                            Position = "Finance Officer"
                        },
                        new
                        {
                            Id = new Guid("b3328b36-55b1-4f83-89a4-f2a71d1676ff"),
                            Age = 32,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Yaw Adu",
                            Position = "Business Development Manager"
                        },
                        new
                        {
                            Id = new Guid("ae5c2fd3-e88e-4b85-8b56-c19328eaa04e"),
                            Age = 27,
                            CompanyId = new Guid("b1c97c3f-c2a5-41a2-89d7-4d85a2b3f8a2"),
                            Name = "Esi Boateng",
                            Position = "Logistics Coordinator"
                        },
                        new
                        {
                            Id = new Guid("7b6f35ff-cc73-4968-b63a-c37d34e2a1bc"),
                            Age = 31,
                            CompanyId = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Name = "Kwame Asiedu",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("50335f56-f68f-46f1-a7b1-e348da34c7ac"),
                            Age = 28,
                            CompanyId = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Name = "Akosua Dwamena",
                            Position = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("9d6a2b1c-ecba-44c5-bc8b-8cfe55cb37f7"),
                            Age = 34,
                            CompanyId = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Name = "Yaw Mensah",
                            Position = "Senior Developer"
                        },
                        new
                        {
                            Id = new Guid("b36bcd61-08f4-4d45-b0fa-404eb38d85f0"),
                            Age = 29,
                            CompanyId = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Name = "Kojo Amankwah",
                            Position = "Data Analyst"
                        },
                        new
                        {
                            Id = new Guid("4319e7c1-b201-4c91-b417-9f5f31b9fc52"),
                            Age = 30,
                            CompanyId = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Name = "Abena Duodu",
                            Position = "Business Intelligence Analyst"
                        },
                        new
                        {
                            Id = new Guid("f38035e7-d2ad-4204-91ad-7315206019b1"),
                            Age = 32,
                            CompanyId = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Name = "Yaw Kofi",
                            Position = "Quality Assurance Specialist"
                        },
                        new
                        {
                            Id = new Guid("8d16f3e4-1a2b-470d-94c3-c71208e60a72"),
                            Age = 31,
                            CompanyId = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Name = "Martha Nana",
                            Position = "System Administrator"
                        },
                        new
                        {
                            Id = new Guid("b5cb9d4c-5a57-402f-bb67-eab6587ffb68"),
                            Age = 28,
                            CompanyId = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Name = "Akosua Esi",
                            Position = "Support Engineer"
                        },
                        new
                        {
                            Id = new Guid("add02f5c-986e-4b77-ae7d-bf8cf1ad00f1"),
                            Age = 27,
                            CompanyId = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Name = "Yaw Nkrumah",
                            Position = "Operations Assistant"
                        },
                        new
                        {
                            Id = new Guid("c617b3ab-712b-4a60-bb1d-2a1c51f15a97"),
                            Age = 29,
                            CompanyId = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Name = "Kojo Essien",
                            Position = "Product Manager"
                        },
                        new
                        {
                            Id = new Guid("50ac0be1-7bb1-4d04-b6b2-03b0638fd5f5"),
                            Age = 30,
                            CompanyId = new Guid("a5e9d3c8-f3c8-4791-b7a9-3d74c8b6d5e9"),
                            Name = "Abena Akua",
                            Position = "Accountant"
                        },
                        new
                        {
                            Id = new Guid("e25cd883-c5d4-40e2-8ed3-531dfedb2118"),
                            Age = 32,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Kwame Owusu",
                            Position = "Marine Engineer"
                        },
                        new
                        {
                            Id = new Guid("d59c4b82-fadf-49fc-bd57-8a745e6f85e4"),
                            Age = 28,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Akosua Asante",
                            Position = "Shipping Coordinator"
                        },
                        new
                        {
                            Id = new Guid("8e77a2bb-3fe4-468d-8397-9d7dff6a6719"),
                            Age = 34,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Yaw Adu",
                            Position = "Logistics Manager"
                        },
                        new
                        {
                            Id = new Guid("0b8ffb1f-2292-4135-8b89-490c8d8dfae0"),
                            Age = 29,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Kojo Osei",
                            Position = "Port Operations Officer"
                        },
                        new
                        {
                            Id = new Guid("06d8d55a-0e78-4448-b453-abead4cd522e"),
                            Age = 31,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Abena Boateng",
                            Position = "Fleet Coordinator"
                        },
                        new
                        {
                            Id = new Guid("1b7f6b10-2396-417d-b9c1-7a31e5814727"),
                            Age = 33,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Yaw Frimpong",
                            Position = "Marine Surveyor"
                        },
                        new
                        {
                            Id = new Guid("d48c5057-24bc-44b0-a847-49e02dbd49d5"),
                            Age = 32,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Kojo Appiah",
                            Position = "Marine Logistics Specialist"
                        },
                        new
                        {
                            Id = new Guid("08d764ef-6226-4c83-8ae9-8bdb85ed7ff6"),
                            Age = 30,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Martha Annan",
                            Position = "Docking Supervisor"
                        },
                        new
                        {
                            Id = new Guid("b0b75517-bc7e-4fa5-bb6b-c77356e82098"),
                            Age = 29,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Yaw Kwaku",
                            Position = "Cargo Handling Manager"
                        },
                        new
                        {
                            Id = new Guid("27999ad6-b49d-472b-924a-5e24f795d249"),
                            Age = 30,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Akosua Afia",
                            Position = "Operations Assistant"
                        },
                        new
                        {
                            Id = new Guid("935e1d07-1534-476f-beb4-92b964772477"),
                            Age = 28,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Kojo Asiedu",
                            Position = "Logistics Coordinator"
                        },
                        new
                        {
                            Id = new Guid("4d5f2e34-0db9-488d-b0b5-67295d902ff9"),
                            Age = 31,
                            CompanyId = new Guid("e4c8b5f3-d2f7-41a7-a8b4-9f6d5b7c4e3b"),
                            Name = "Yaw Owusu",
                            Position = "Compliance Officer"
                        },
                        new
                        {
                            Id = new Guid("e318d209-26fc-4874-a533-956bd84589b5"),
                            Age = 31,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Kwame Boakye",
                            Position = "Software Developer"
                        },
                        new
                        {
                            Id = new Guid("68bbaaf0-32a0-4b8d-bb42-f6c23f20b03f"),
                            Age = 29,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Akosua Amankwah",
                            Position = "Web Developer"
                        },
                        new
                        {
                            Id = new Guid("bda1ea26-c52b-47be-b697-68273a7bdbdf"),
                            Age = 34,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Yaw Boateng",
                            Position = "Mobile App Developer"
                        },
                        new
                        {
                            Id = new Guid("aad9a410-13a4-44f2-8d38-acc99ad5c5e3"),
                            Age = 28,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Kojo Asamoah",
                            Position = "Backend Developer"
                        },
                        new
                        {
                            Id = new Guid("91ff2e2b-caa2-4733-86c7-7481e55cb690"),
                            Age = 30,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Abena Fosu",
                            Position = "Front-end Developer"
                        },
                        new
                        {
                            Id = new Guid("174f4ef9-5bdf-4b67-95fe-19fd3361b5b7"),
                            Age = 32,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Yaw Baffour",
                            Position = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("5f018cf4-0d51-4644-b381-62debb0620b6"),
                            Age = 33,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Martha Osei",
                            Position = "DevOps Engineer"
                        },
                        new
                        {
                            Id = new Guid("93917c27-d504-47e7-8b50-2c2ca5b3d8b7"),
                            Age = 28,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Kojo Quartey",
                            Position = "Database Administrator"
                        },
                        new
                        {
                            Id = new Guid("a7e5561e-1d9e-42fd-b4f8-f9b5e6512d08"),
                            Age = 30,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Yaw Nyarko",
                            Position = "Quality Assurance Engineer"
                        },
                        new
                        {
                            Id = new Guid("f9e22d29-2d93-4cbe-b926-dc5b14bbf5a7"),
                            Age = 29,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Kojo Attah",
                            Position = "UI/UX Designer"
                        },
                        new
                        {
                            Id = new Guid("5c1c38b1-d57e-4d9b-95f7-e38b91c61b50"),
                            Age = 32,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Akosua Kofi",
                            Position = "Systems Analyst"
                        },
                        new
                        {
                            Id = new Guid("42a35b11-bc80-417a-8966-3ea6f06e08ec"),
                            Age = 35,
                            CompanyId = new Guid("c7f6b4d2-8f7b-43c5-a9e3-2d1f4c6b7a3c"),
                            Name = "Yaw Duodu",
                            Position = "Technical Support Engineer"
                        });
                });

            modelBuilder.Entity("WorkforceHubAPI.Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WorkforceHubAPI.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WorkforceHubAPI.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkforceHubAPI.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WorkforceHubAPI.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkforceHubAPI.Entities.Models.Employee", b =>
                {
                    b.HasOne("WorkforceHubAPI.Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WorkforceHubAPI.Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
